version: '3'

dotenv: ['config.env']

includes:
  app:
    taskfile: ./app/Taskfile.yml
    dir: ./app

tasks:
  _get_taskutils:
    cmds:
      - git clone --no-checkout https://github.com/gerbillinae/taskutils
      - defer: rm -rf ./taskutils
      - cd taskutils; git fetch origin ${TASKUTILS_COMMIT}
      - cd taskutils; git checkout ${TASKUTILS_COMMIT}
      - task --taskfile taskutils/Taskfile.yaml build
      - mkdir -p .taskfile/bin || true
      - mv taskutils/bin/* .taskfile/bin
      - chmod +rx .taskfile/bin/*

  init:
    cmds:
      - task: _get_taskutils

  test_package:
    dotenv: ['build/package.env']
    cmds:
      - docker run -d -p 8080:8080 ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)
      - defer: docker ps -a | grep ${IMAGE_NAMESPACE}/${IMAGE_NAME} | awk '{print $1}' | xargs -n 1 docker kill | xargs -n 1 docker remove
      - python3 test/test.py --address "http://localhost:${APP_PORT}"

  build:
    cmds:
      - task: app:build
      - rm -r ./build
      - mv ./app/build .
      - IMAGE_VERSION=$(git rev-parse HEAD) ./.taskfile/bin/hydrate ./templates/package.template.env > ./build/package.env
      - IMAGE_VERSION=$(git rev-parse HEAD) ./.taskfile/bin/hydrate ./templates/config.template.json > ./build/config.json
      - check-jsonschema --schemafile build/config.schema.json build/config.json

  package:
    cmds:
      - task: build
      - docker build --platform linux/${GOARCH} -t ${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest  -f ./Dockerfile ./build
      - docker tag ${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)
      - echo ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse --short HEAD)
      - task: test_package

  _push_container_to_aws_ecr:
    cmds:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${CONTAINER_REGISTRY}
      - aws ecr create-repository --repository-name ${IMAGE_NAMESPACE}/${IMAGE_NAME} || true
      - docker tag ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD) ${CONTAINER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)
      - docker push ${CONTAINER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)

  _generate_deployment_files:
    cmds:
      - IMAGE_VERSION=$(git rev-parse HEAD) ./.taskfile/bin/hydrate ./templates/deployment.template.k8s.yaml > ./build/deployment.k8s.yaml

  deploy:
    preconditions:
      - sh: git diff-index --quiet HEAD || false
        msg: "The current git repository is dirty."
    cmds:
      - task: package
      - task: _generate_deployment_files
      - grep $(git rev-parse HEAD) ./build/deployment.k8s.yaml
      - task: _push_container_to_aws_ecr
      - kubectl apply -f ./build/deployment.k8s.yaml

  deployment-test:
    cmds:
      - python3 test.py --address "${DEPLOYMENT_URL}"
