version: '3'

dotenv: ['config.env']

tasks:
  _get_taskutils:
    cmds:
      - git clone --no-checkout https://github.com/gerbillinae/taskutils
      - defer: rm -rf ./taskutils
      - cd taskutils; git fetch origin ${TASKUTILS_COMMIT}
      - cd taskutils; git checkout ${TASKUTILS_COMMIT}
      - task --taskfile taskutils/Taskfile.yaml build
      - mkdir -p .taskfile/bin || true
      - mv taskutils/bin/* .taskfile/bin
      - chmod +rx .taskfile/bin/*

  init:
    cmds:
      - task: _get_taskutils

  _package_test:
    dotenv: ['build/package.env']
    cmds:
      - echo docker run -d -p 8080:8080 ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}
      - docker run -d -p 8080:8080 ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}
      - defer: docker ps -a | grep ${IMAGE_NAMESPACE}/${IMAGE_NAME} | awk '{print $1}' | xargs -n 1 docker kill | xargs -n 1 docker remove
      - python3 test/test.py --address "${LOCAL_URL}"

  build:
    cmds:
      - mkdir build || true
      - GOOS=linux GOARCH=${ARCH} go build -o build/main ./src/main.go
      - IMAGE_VERSION=$(git rev-parse HEAD) ./.taskfile/bin/hydrate ./templates/package.template.env > build/package.env

  package:
    cmds:
      - task: build
      - docker build --platform linux/${ARCH} -t ${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest  -f ./Dockerfile ./build
      - docker tag ${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)
      - echo ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse --short HEAD)
      - task: _package_test

  _push_container_to_aws_ecr:
    cmds:
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${CONTAINER_REGISTRY}
      - aws ecr create-repository --repository-name ${IMAGE_NAMESPACE}/${IMAGE_NAME} || true
      - docker tag ${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD) ${CONTAINER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)
      - docker push ${CONTAINER_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:$(git rev-parse HEAD)

  _generate_deployment_files:
    cmds:
      - rm -r deployment || true
      - mkdir deployment
      - IMAGE_VERSION=$(git rev-parse HEAD) ./.taskfile/bin/hydrate ./templates/k8s-deployment.template.yaml > ./deployment/k8s-deployment.yaml

  deploy:
    preconditions:
      - sh: git diff-index --quiet HEAD || false
        msg: "The current git repository is dirty."
    cmds:
      - task: package
      - task: _generate_deployment_files
      - task: _push_container_to_aws_ecr
      - kubectl apply -f ./deployment/k8s-deployment.yaml

  deployment-test:
    cmds:
      - python3 test.py --address "${DEPLOYMENT_URL}"
